# Chapter 11. Using other languages

In [1]:
pwd()

"C:\\Users\\user"

### ⚫Python

In [2]:
using PyCall

I can import any python package...

In [3]:
math = pyimport("math")

PyObject <module 'math' (built-in)>

In [4]:
math.sin(math.pi/4)

0.7071067811865476

In [5]:
python_networkx = pyimport("networkx")

LoadError: PyError (PyImport_ImportModule

The Python package networkx could not be imported by pyimport. Usually this means
that you did not install networkx in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the networkx module, you can
use `pyimport_conda("networkx", PKG)`, where PKG is the Anaconda
package the contains the module networkx, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'networkx'")


I can also write my own Python code as follows

In [6]:
py"""
import numpy as np
def find_best_fit_python(xvals, yvals):
    meanx = np.mean(xvals)
    meany = np.mean(yvals)
    stdx = np.std(xvals)
    stdy = np.std(yvals)
    r = np.corrcoef(xvals, yvals)[0][1]
    a = r*stdy/stdx
    b = meany - a*meanx
    return a, b
"""

In [7]:
xvals = repeat(1:0.5:10, inner = 2)

38-element Vector{Float64}:
  1.0
  1.0
  1.5
  1.5
  2.0
  2.0
  2.5
  2.5
  3.0
  3.0
  3.5
  3.5
  4.0
  ⋮
  7.5
  7.5
  8.0
  8.0
  8.5
  8.5
  9.0
  9.0
  9.5
  9.5
 10.0
 10.0

In [8]:
yvals = 3 .+ xvals .+ 2 .* rand(length(xvals)) .-1

38-element Vector{Float64}:
  3.6411084708879837
  3.8129553264968736
  5.357263837517872
  5.138378004343799
  5.1611333885054655
  5.306203248726896
  5.611073860469678
  4.960555428618479
  6.824691248920548
  6.445213754900239
  6.558131819113468
  6.006765551993816
  6.279425596642828
  ⋮
 11.31533636636851
  9.569795678415966
 11.12894086656191
 11.502118768965085
 11.237955125987405
 11.257637932916916
 12.232272184175601
 12.209908860534654
 13.107850049036466
 12.943059675508321
 13.834941150001274
 12.672618648053938

In [9]:
find_best_fit_python = py"find_best_fit_python"

PyObject <function find_best_fit_python at 0x0000000040FB33A0>

In [10]:
a, b = find_best_fit_python(xvals, yvals)

(1.0123567405195144, 2.9708183209983643)

If the above python code was in a file called `fit_linear.py`, you can call it as follows:
```
python_linear_fit = pyimport("fit_linear") 
python_linear_fit.find_best_fit_python(xvals,yvals)```

### ⚫R code

In [11]:
using RCall

`$` can switch to an `R` REPL from julia's REPL. We'll take a look...

In [12]:
# we can use the rcall function
r = rcall(:sum, Float64[1.0, 4.0, 6.0])

RObject{RealSxp}
[1] 11


In [13]:
typeof(r[1])

Float64

In [14]:
size(r)

(1,)

The `@rput` allows you to put julia variable in the `R` context.
- @rput을 사용하면 R 컨텍스트에 줄리아 변수를 넣을 수 있음

In [15]:
z = 1

1

In [16]:
@rput z

1

In [17]:
r = R"z+z"

RObject{IntSxp}
[1] 2


In [18]:
r[1]

2

In [19]:
x = randn(10)

10-element Vector{Float64}:
 -1.3066836535260846
  0.6427395344816944
 -0.8473052315128197
 -1.2547903455837228
 -0.7744702140985408
 -0.668659097586767
  1.2582134594394876
 -1.2011062003996467
  1.1709972008007166
 -1.047434489145865

You can apply R functions on julia variables

In [20]:
@rimport base as rbase

In [21]:
rbase.sum([1, 2, 3])

RObject{IntSxp}
[1] 6


In [22]:
@rlibrary boot

In [23]:
# @rlibrary ggplot2

In [24]:
R"sessionInfo()"

RObject{VecSxp}
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949   
[3] LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                
[5] LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4 boot_1.3-26   


In [25]:
R"getwd()"

RObject{StrSxp}
[1] "C:/Users/user"


In [28]:
R"R.home()"

RObject{StrSxp}
[1] "C:/Program Files/R/R-4.0.4"


In [30]:
R"Sys.getenv('R_HOME')"

RObject{StrSxp}
[1] "C:/Program Files/R/R-4.0.4"


In [31]:
@rlibrary rpart

In [32]:
R"t.test(x)"

LoadError: REvalError: Error in t.test(x) : object 'x' not found

In [33]:
R"t.test($x)"

RObject{VecSxp}

	One Sample t-test

data:  `#JL`$x
t = -1.2511, df = 9, p-value = 0.2424
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -1.1312466  0.3255468
sample estimates:
 mean of x 
-0.4028499 



In [34]:
using HypothesisTests

In [35]:
OneSampleTTest(x)

One sample t-test
-----------------
Population details:
    parameter of interest:   Mean
    value under h_0:         0
    point estimate:          -0.40285
    95% confidence interval: (-1.1312, 0.3255)

Test summary:
    outcome with 95% confidence: fail to reject h_0
    two-sided p-value:           0.2424

Details:
    number of observations:   10
    t-statistic:              -1.2511174569063175
    degrees of freedom:       9
    empirical standard error: 0.3219920731577801
