# 줄리아 연습 1

## 학습자료: 줄리아 아카데미 강의자료 (https://github.com/JuliaAcademy/DataScience)
- Julia for Data Science - Video 1: Data, by Dr. Huda Nassar (for JuliaAcademy.com)
- youtube 

## 1. 환경 확인

In [93]:
pwd()

"C:\\Users\\user"

### Package 사용 

- 패키지 로딩 명령어 : using 또는 import (R의 library, Python의 import에 해당)

#### import와 loading의 차이점
- Package loading: e.g. import X or using X. The import mechanism allows you to load a package—i.e. an independent, reusable collection of Julia code, wrapped in a module—and makes the resulting module available by the name X inside of the importing module. If the same X package is imported multiple times in the same Julia session, it is only loaded the first time—on subsequent imports, the importing module gets a reference to the same module. Note though, that import X can load different packages in different contexts: X can refer to one package named X in the main project but potentially to different packages also named X in each dependency. More on this below.
- https://docs.julialang.org/en/v1/manual/code-loading/

In [2]:
using Pkg

In [3]:
using BenchmarkTools
using DataFrames
using DelimitedFiles
using CSV
using XLSX

┌ Info: Recompiling stale cache file C:\Users\user\.julia\compiled\v1.0\BenchmarkTools\ZXPQo.ji for BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
└ @ Base loading.jl:1190
┌ Info: Recompiling stale cache file C:\Users\user\.julia\compiled\v1.0\DataFrames\AR9oZ.ji for DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1190
┌ Info: Recompiling stale cache file C:\Users\user\.julia\compiled\v1.0\CSV\HHBkp.ji for CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
└ @ Base loading.jl:1190


In [4]:
P = download("https://raw.githubusercontent.com/nassarhuda/easy_data/master/programming_languages.csv",
    "programminglanguages.csv")

"programminglanguages.csv"

In [5]:
pwd()

"C:\\Users\\user"

In [6]:
readdir()

49-element Array{String,1}:
 ".conda"                       
 ".condarc"                     
 ".ipynb_checkpoints"           
 ".ipython"                     
 ".julia"                       
 ".jupyter"                     
 ".matplotlib"                  
 "3D Objects"                   
 "anaconda3"                    
 "AppData"                      
 "Application Data"             
 "Contacts"                     
 "Cookies"                      
 ⋮                              
 "promgramminglanguages_CSV.CSV"
 "Recent"                       
 "RL"                           
 "Saved Games"                  
 "Searches"                     
 "SendTo"                       
 "Templates"                    
 "test_df.xlsx"                 
 "Untitled.ipynb"               
 "Videos"                       
 "writefile_using_XLSX.xlsx"    
 "시작 메뉴"                        

In [7]:
C = CSV.read("programminglanguages.csv", DataFrame);

# CSV.read에서 파일 경로와 불러들일 데이터 타입을 함께 지정해야 함

In [8]:
# 불러들인 데이터의 타입 확인
@show typeof(C)

typeof(C) = DataFrame


DataFrame

In [9]:
typeof(C)

DataFrame

In [10]:
# 데이터 스플릿
C[1:10, :]

10×2 DataFrame
 Row │ year   language                   
     │ Int64  String                     
─────┼───────────────────────────────────
   1 │  1951  Regional Assembly Language
   2 │  1952  Autocode
   3 │  1954  IPL
   4 │  1955  FLOW-MATIC
   5 │  1957  FORTRAN
   6 │  1957  COMTRAN
   7 │  1958  LISP
   8 │  1958  ALGOL 58
   9 │  1959  FACT
  10 │  1959  COBOL

In [11]:
P,H = readdlm("programminglanguages.csv",',';header=true);

In [12]:
typeof(P)

Array{Any,2}

In [13]:
P[1:5, :]

5×2 Array{Any,2}:
 1951  "Regional Assembly Language"
 1952  "Autocode"                  
 1954  "IPL"                       
 1955  "FLOW-MATIC"                
 1957  "FORTRAN"                   

In [14]:
H

1×2 Array{AbstractString,2}:
 "year"  "language"

In [15]:
names(C)

2-element Array{String,1}:
 "year"    
 "language"

In [16]:
C.year[1:6]

6-element Array{Int64,1}:
 1951
 1952
 1954
 1955
 1957
 1957

In [17]:
C.language[1:6]

6-element Array{String,1}:
 "Regional Assembly Language"
 "Autocode"                  
 "IPL"                       
 "FLOW-MATIC"                
 "FORTRAN"                   
 "COMTRAN"                   

In [18]:
# 기초 통계량 산출
describe(C)

2×7 DataFrame
 Row │ variable  mean     min       median  max        nmissing  eltype   
     │ Symbol    Union…   Any       Union…  Any        Int64     DataType 
─────┼────────────────────────────────────────────────────────────────────
   1 │ year      1982.99  1951      1986.0  2014              0  Int64
   2 │ language           ALGOL 58          dBase III         0  String

### 속도 비교

In [19]:
@btime P,H = readdlm("programminglanguages.csv",',';header=true);
@btime C = CSV.read("programminglanguages.csv", DataFrame);

  124.299 μs (313 allocations: 50.73 KiB)
  141.000 μs (236 allocations: 22.53 KiB)


### CSV로 내보내기

In [20]:
CSV.write("promgramminglanguages_CSV.CSV", DataFrame(P, :auto))

"promgramminglanguages_CSV.CSV"

### XLSX 읽어들이기

In [21]:
T = XLSX.readdata("C:/Users/user/DataScience-main/data/zillow_data_download_april2020.xlsx", #file name
    "Sale_counts_city", #sheet name
    "A1:F9" #cell range
    )

9×6 Array{Any,2}:
      "RegionID"  "RegionName"    …      "2008-03"      "2008-04"
  6181            "New York"             missing        missing  
 12447            "Los Angeles"      1446           1705         
 39051            "Houston"          2926           3121         
 17426            "Chicago"          2910           3022         
  6915            "San Antonio"   …  1479           1529         
 13271            "Philadelphia"     1609           1795         
 40326            "Phoenix"          1310           1519         
 18959            "Las Vegas"        1618           1856         

In [22]:
T
# matrix 형태로 불러들임

9×6 Array{Any,2}:
      "RegionID"  "RegionName"    …      "2008-03"      "2008-04"
  6181            "New York"             missing        missing  
 12447            "Los Angeles"      1446           1705         
 39051            "Houston"          2926           3121         
 17426            "Chicago"          2910           3022         
  6915            "San Antonio"   …  1479           1529         
 13271            "Philadelphia"     1609           1795         
 40326            "Phoenix"          1310           1519         
 18959            "Las Vegas"        1618           1856         

### DataFrame (줄리아에서 데이터 프레임) 

In [23]:
?DataFrame

search: DataFrame DataFrame! DataFrames DataFrameRow SubDataFrame



```
DataFrame <: AbstractDataFrame
```

An AbstractDataFrame that stores a set of named columns

The columns are normally AbstractVectors stored in memory, particularly a Vector or CategoricalVector.

# Constructors

```julia
DataFrame(pairs::Pair...; makeunique::Bool=false, copycols::Bool=true)
DataFrame(pairs::AbstractVector{<:Pair}; makeunique::Bool=false, copycols::Bool=true)
DataFrame(ds::AbstractDict; copycols::Bool=true)
DataFrame(kwargs..., copycols::Bool=true)

DataFrame(columns::AbstractVecOrMat, names::Union{AbstractVector, Symbol};
          makeunique::Bool=false, copycols::Bool=true)

DataFrame(table; copycols::Bool=true)
DataFrame(::DataFrameRow)
DataFrame(::GroupedDataFrame; keepkeys::Bool=true)
```

# Keyword arguments

  * `copycols` : whether vectors passed as columns should be copied; by default set to `true` and the vectors are copied; if set to `false` then the constructor will still copy the passed columns if it is not possible to construct a `DataFrame` without materializing new columns.
  * `makeunique` : if `false` (the default), an error will be raised

(note that not all constructors support these keyword arguments)

# Details on behavior of different constructors

It is allowed to pass a vector of `Pair`s, a list of `Pair`s as positional arguments, or a list of keyword arguments. In this case each pair is considered to represent a column name to column value mapping and column name must be a `Symbol` or string. Alternatively a dictionary can be passed to the constructor in which case its entries are considered to define the column name and column value pairs. If the dictionary is a `Dict` then column names will be sorted in the returned `DataFrame`.

In all the constructors described above column value can be a vector which is consumed as is or an object of any other type (except `AbstractArray`). In the latter case the passed value is automatically repeated to fill a new vector of the appropriate length. As a particular rule values stored in a `Ref` or a `0`-dimensional `AbstractArray` are unwrapped and treated in the same way.

It is also allowed to pass a vector of vectors or a matrix as as the first argument. In this case the second argument must be a vector of `Symbol`s or strings specifying column names, or the symbol `:auto` to generate column names `x1`, `x2`, ... automatically.

If a single positional argument is passed to a `DataFrame` constructor then it is assumed to be of type that implements the [Tables.jl](https://github.com/JuliaData/Tables.jl) interface using which the returned `DataFrame` is materialized.

Finally it is allowed to construct a `DataFrame` from a `DataFrameRow` or a `GroupedDataFrame`. In the latter case the `keepkeys` keyword argument specifies whether the resulting `DataFrame` should contain the grouping columns of the passed `GroupedDataFrame` and the order of rows in the result follows the order of groups in the `GroupedDataFrame` passed.

# Notes

The `DataFrame` constructor by default copies all columns vectors passed to it. Pass the `copycols=false` keyword argument (where supported) to reuse vectors without copying them.

By default an error will be raised if duplicates in column names are found. Pass `makeunique=true` keyword argument (where supported) to accept duplicate names, in which case they will be suffixed with `_i` (`i` starting at 1 for the first duplicate).

If an `AbstractRange` is passed to a `DataFrame` constructor as a column it is always collected to a `Vector` (even if `copycols=false`). As a general rule `AbstractRange` values are always materialized to a `Vector` by all functions in DataFrames.jl before being stored in a `DataFrame`.

The `DataFrame` type is designed to allow column types to vary and to be dynamically changed also after it is constructed. Therefore `DataFrame`s are not type stable. For performance-critical code that requires type-stability either use the functionality provided by `select`/`transform`/`combine` functions, use `Tables.columntable` and `Tables.namedtupleiterator` functions, use barrier functions, or provide type assertions to the variables that hold columns extracted from a `DataFrame`.

# Examples

```julia
julia> DataFrame((a=[1, 2], b=[3, 4])) # Tables.jl table constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      3
   2 │     2      4

julia> DataFrame([(a=1, b=0), (a=2, b=0)]) # Tables.jl table constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0

julia> DataFrame("a" => 1:2, "b" => 0) # Pair constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0

julia> DataFrame([:a => 1:2, :b => 0]) # vector of Pairs constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0

julia> DataFrame(Dict(:a => 1:2, :b => 0)) # dictionary constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0

julia> DataFrame(a=1:2, b=0) # keyword argument constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0

julia> DataFrame([[1, 2], [0, 0]], [:a, :b]) # vector of vectors constructor
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0

julia> DataFrame([1 0; 2 0], :auto) # matrix constructor
2×2 DataFrame
 Row │ x1     x2
     │ Int64  Int64
─────┼──────────────
   1 │     1      0
   2 │     2      0
```


In [24]:
# XLSX 패키지의 readtable로 읽어들이기 -> 두개의 튜플로 읽어들임 (하나는 각 컬럼들이 원소(벡터)가 되는 원소, 다른 하나는 컬럼명)
# -> 어레이 형태가 됨
G = XLSX.readtable("C:/Users/user/DataScience-main/data/zillow_data_download_april2020.xlsx", "Sale_counts_city");

In [25]:
G[1][1][1:10]

10-element Array{Any,1}:
  6181
 12447
 39051
 17426
  6915
 13271
 40326
 18959
 54296
 38128

In [26]:
G[2][1:10]

10-element Array{Symbol,1}:
 :RegionID        
 :RegionName      
 :StateName       
 :SizeRank        
 Symbol("2008-03")
 Symbol("2008-04")
 Symbol("2008-05")
 Symbol("2008-06")
 Symbol("2008-07")
 Symbol("2008-08")

In [27]:
D = DataFrame(G...) # equivalent to DataFrame(G[1],G[2]) #...을 splat operator라고 함

28759×148 DataFrame
   Row │ RegionID  RegionName                  StateName      SizeRank  2008-0 ⋯
       │ Any       Any                         Any            Any       Any    ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │ 6181      New York                    New York       1         missin ⋯
     2 │ 12447     Los Angeles                 California     2         1446
     3 │ 39051     Houston                     Texas          3         2926
     4 │ 17426     Chicago                     Illinois       4         2910
     5 │ 6915      San Antonio                 Texas          5         1479   ⋯
     6 │ 13271     Philadelphia                Pennsylvania   6         1609
     7 │ 40326     Phoenix                     Arizona        7         1310
     8 │ 18959     Las Vegas                   Nevada         8         1618
     9 │ 54296     San Diego                   California     9         772    ⋯
    10 │ 38128     Dallas                      Texas          10        1158
    11 │ 10221     Austin                      Texas          11        997
   ⋮   │    ⋮                  ⋮                     ⋮           ⋮         ⋮   ⋱
 28750 │ 396952    Barnard Plantation          Maine          28750     0
 28751 │ 397236    Windsor Place               Missouri       28751     0      ⋯
 28752 │ 398030    Stockbridge                 Wisconsin      28752     0
 28753 │ 398104    Mattamiscontis              Maine          28753     0
 28754 │ 398357    Chase Stream                Maine          28754     0
 28755 │ 398712    Bowdoin College Grant West  Maine          28755     0      ⋯
 28756 │ 398716    Summerset                   South Dakota   28756     0
 28757 │ 399081    Long Pond                   Maine          28757     0
 28758 │ 737789    Hideout                     Utah           28758     1
 28759 │ 760882    Ebeemee                     Maine          28759     0      ⋯
                                              144 columns and 28738 rows omitted

In [28]:
foods = ["apple", "cucumber", "tomato", "banana"]
calories = [105, 47, 22, 105]
prices = [0.85, 1.6, 0.8, 0.6 ]
dataframe_calories = DataFrame(item = foods, calories = calories)
dataframe_prices = DataFrame(item = foods, price = prices)

4×2 DataFrame
 Row │ item      price   
     │ String    Float64 
─────┼───────────────────
   1 │ apple        0.85
   2 │ cucumber     1.6
   3 │ tomato       0.8
   4 │ banana       0.6

In [29]:
DF = innerjoin(dataframe_calories, dataframe_prices, on = :item)

4×3 DataFrame
 Row │ item      calories  price   
     │ String    Int64     Float64 
─────┼─────────────────────────────
   1 │ apple          105     0.85
   2 │ cucumber        47     1.6
   3 │ tomato          22     0.8
   4 │ banana         105     0.6

#### matrix를 dataframe으로 바꾸기

In [30]:
# 주의점: Warning: `DataFrame(columns::AbstractMatrix)` is deprecated, use `DataFrame(columns, :auto)` instead
DataFrame(T, :auto)

9×6 DataFrame
 Row │ x1        x2            x3            x4        x5       x6      
     │ Any       Any           Any           Any       Any      Any     
─────┼──────────────────────────────────────────────────────────────────
   1 │ RegionID  RegionName    StateName     SizeRank  2008-03  2008-04
   2 │ 6181      New York      New York      1         missing  missing 
   3 │ 12447     Los Angeles   California    2         1446     1705
   4 │ 39051     Houston       Texas         3         2926     3121
   5 │ 17426     Chicago       Illinois      4         2910     3022
   6 │ 6915      San Antonio   Texas         5         1479     1529
   7 │ 13271     Philadelphia  Pennsylvania  6         1609     1795
   8 │ 40326     Phoenix       Arizona       7         1310     1519
   9 │ 18959     Las Vegas     Nevada        8         1618     1856

In [31]:
# 데이터 프레임으로 내보내기 
# 
# XLSX.writetable("filename.xlsx", collect(DataFrames.eachcol(df)), DataFrames.names(df))
XLSX.writetable("writefile_using_XLSX.xlsx",G[1],G[2])

AssertionError: AssertionError: writefile_using_XLSX.xlsx already exists.

In [32]:
XLSX.writetable("test_df.xlsx", DF) # 성공적으로 xlsx에 저장됨

AssertionError: AssertionError: test_df.xlsx already exists.

### 데이터 과학 언어들의 데이터 불러오기(jld, npz, rda, mat)

In [33]:
using JLD

ArgumentError: ArgumentError: Package JLD not found in current path:
- Run `import Pkg; Pkg.add("JLD")` to install the JLD package.


In [40]:
using FileIO

ArgumentError: ArgumentError: Package FileIO not found in current path:
- Run `import Pkg; Pkg.add("FileIO")` to install the FileIO package.


In [41]:
Pkg.add("FileIO");

 Resolving package versions...
 Installed Requires ─ v1.1.3
 Installed FileIO ─── v1.6.5
  Updating `C:\Users\user\.julia\environments\v1.0\Project.toml`
  [5789e2e9] + FileIO v1.6.5
  Updating `C:\Users\user\.julia\environments\v1.0\Manifest.toml`
  [5789e2e9] + FileIO v1.6.5
  [ae029012] + Requires v1.1.3


In [42]:
Pkg.add("JLD")

 Resolving package versions...


Pkg.Types.ResolverError: Unsatisfiable requirements detected for package Blosc [a74b3585]:
 Blosc [a74b3585] log:
 ├─possible versions are: [0.5.1, 0.6.0, 0.7.0] or uninstalled
 ├─restricted by julia compatibility requirements to versions: [0.5.1, 0.6.0] or uninstalled
 ├─restricted by compatibility requirements with HDF5 [f67ccb44] to versions: 0.5.1
 │ └─HDF5 [f67ccb44] log:
 │   ├─possible versions are: [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5, 0.13.0-0.13.7, 0.14.0-0.14.3, 0.15.0-0.15.4] or uninstalled
 │   ├─restricted by julia compatibility requirements to versions: [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5] or uninstalled
 │   └─restricted by compatibility requirements with JLD [4138dd39] to versions: [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5, 0.13.0-0.13.7], leaving only versions: [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5]
 │     └─JLD [4138dd39] log:
 │       ├─possible versions are: [0.9.0-0.9.2, 0.10.0, 0.11.0-0.11.1, 0.12.0-0.12.2] or uninstalled
 │       ├─restricted to versions * by an explicit requirement, leaving only versions [0.9.0-0.9.2, 0.10.0, 0.11.0-0.11.1, 0.12.0-0.12.2]
 │       ├─restricted by julia compatibility requirements to versions: [0.9.0-0.9.2, 0.10.0] or uninstalled, leaving only versions: [0.9.0-0.9.2, 0.10.0]
 │       └─restricted by compatibility requirements with Compat [34da2185] to versions: [0.9.2, 0.10.0, 0.11.0-0.11.1, 0.12.0-0.12.2] or uninstalled, leaving only versions: [0.9.2, 0.10.0]
 │         └─Compat [34da2185] log:
 │           ├─possible versions are: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0-2.2.1, 3.0.0, 3.1.0, 3.2.0, 3.3.0-3.3.1, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0, 3.11.0, 3.12.0, 3.13.0, 3.14.0, 3.15.0, 3.16.0, 3.17.0, 3.18.0, 3.19.0, 3.20.0, 3.21.0, 3.22.0, 3.23.0, 3.24.0, 3.25.0] or uninstalled
 │           └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: [3.17.0, 3.18.0, 3.19.0, 3.20.0, 3.21.0, 3.22.0, 3.23.0, 3.24.0, 3.25.0]
 │             └─DataFrames [a93c6f00] log:
 │               ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.8, 0.22.0-0.22.6] or uninstalled
 │               └─restricted to versions 0.22.6 by an explicit requirement, leaving only versions 0.22.6
 └─restricted by compatibility requirements with Compat [34da2185] to versions: [0.6.0, 0.7.0] or uninstalled — no versions left
   └─Compat [34da2185] log: see above

In [36]:
jld_data = JLD.load("C:/Users/user/DataScience-main/data/mytempdata.jld")

UndefVarError: UndefVarError: JLD not defined

### JLD는 안되고...
### NPZ 시도 

In [43]:
using NPZ
npz_data = npzread("DataScience-main/data/mytempdata.npz")
npzwrite("mywrite.npz", npz_data)

ArgumentError: ArgumentError: Package NPZ not found in current path:
- Run `import Pkg; Pkg.add("NPZ")` to install the NPZ package.


In [44]:
Pkg.add("NPZ")

 Resolving package versions...
 Installed NPZ ─ v0.4.1
  Updating `C:\Users\user\.julia\environments\v1.0\Project.toml`
  [15e1cf62] + NPZ v0.4.1
  Updating `C:\Users\user\.julia\environments\v1.0\Manifest.toml`
  [15e1cf62] + NPZ v0.4.1


In [46]:
using NPZ

┌ Info: Precompiling NPZ [15e1cf62-19b3-5cfa-8e77-841668bca605]
└ @ Base loading.jl:1192


SystemError: SystemError: opening file /DataScience-main/data/mytempdata.npz: No such file or directory

In [47]:
npz_data = npzread("DataScience-main/data/mytempdata.npz")
npzwrite("mywrite.npz", npz_data)

### Rdata 불러오기 

In [48]:
using RData
R_data = RData.load("DataScience-main/data/mytempdata.rda")
# We'll need RCall to save here. https://github.com/JuliaData/RData.jl/issues/56


ArgumentError: ArgumentError: Package RData not found in current path:
- Run `import Pkg; Pkg.add("RData")` to install the RData package.


In [49]:
Pkg.add("RData")

 Resolving package versions...
 Installed Mocking ──────────── v0.7.1
 Installed ExprTools ────────── v0.1.3
 Installed CodecZlib ────────── v0.6.0
 Installed RecipesBase ──────── v1.1.1
 Installed RData ────────────── v0.8.0
 Installed TranscodingStreams ─ v0.9.5
 Installed TimeZones ────────── v1.5.3
  Updating `C:\Users\user\.julia\environments\v1.0\Project.toml`
  [df47a6cb] + RData v0.8.0
  Updating `C:\Users\user\.julia\environments\v1.0\Manifest.toml`
  [944b1d66] + CodecZlib v0.6.0
  [e2ba6199] + ExprTools v0.1.3
  [78c3b35d] + Mocking v0.7.1
  [df47a6cb] + RData v0.8.0
  [3cdcf5f2] + RecipesBase v1.1.1
  [f269a46b] + TimeZones v1.5.3
  [3bb67fe8] + TranscodingStreams v0.9.5
  Building TimeZones → `C:\Users\user\.julia\packages\TimeZones\K98G0\deps\build.log`
  Building CodecZlib → `C:\Users\user\.julia\packages\CodecZlib\5t9zO\deps\build.log`


In [50]:
using RData
R_data = RData.load("DataScience-main/data/mytempdata.rda")

┌ Info: Precompiling RData [df47a6cb-8c03-5eed-afd8-b6050d6c41da]
└ @ Base loading.jl:1192


Dict{String,Any} with 1 entry:
  "tempdata" => Int32[2 1446 … 1795 1890; 3 2926 … 3220 3405; 4 2910 … 2937 322…

In [51]:
typeof(R_data)

Dict{String,Any}

In [53]:
print(R_data)

Dict{String,Any}("tempdata"=>Int32[2 1446 1705 1795 1890; 3 2926 3121 3220 3405; 4 2910 3022 2937 3224; 5 1479 1529 1582 1761])

In [54]:
using RCall
@rput R_data
R"save(R_data, file=\"mywrite.rda\")"

ArgumentError: ArgumentError: Package RCall not found in current path:
- Run `import Pkg; Pkg.add("RCall")` to install the RCall package.


In [55]:
Pkg.add("RCall")

 Resolving package versions...
 Installed Rmath ──────────── v0.6.0
 Installed StatsFuns ──────── v0.9.6
 Installed SpecialFunctions ─ v0.8.0
 Installed BinDeps ────────── v1.0.2
 Installed StatsBase ──────── v0.33.4
 Installed StatsModels ────── v0.6.21
 Installed ShiftedArrays ──── v1.0.0
 Installed RCall ──────────── v0.13.10
 Installed WinReg ─────────── v0.3.1
 Installed URIParser ──────── v0.4.1
  Updating `C:\Users\user\.julia\environments\v1.0\Project.toml`
  [6f49c342] + RCall v0.13.10
  Updating `C:\Users\user\.julia\environments\v1.0\Manifest.toml`
  [9e28174c] + BinDeps v1.0.2
  [6f49c342] + RCall v0.13.10
  [79098fc4] + Rmath v0.6.0
  [1277b4bf] + ShiftedArrays v1.0.0
  [276daf66] + SpecialFunctions v0.8.0
  [2913bbd2] + StatsBase v0.33.4
  [4c63d2b9] + StatsFuns v0.9.6
  [3eaba693] + StatsModels v0.6.21
  [30578b45] + URIParser v0.4.1
  [1b915085] + WinReg v0.3.1
  Building SpecialFunctions → `C:\Users\user\.julia\packages\SpecialFunctions\ne2iw\deps\build.log`
  Building

In [57]:
using RCall
@rput R_data
R"save(R_data, file=\"mywrite.rda\")"

┌ Info: Precompiling RCall [6f49c342-dc21-5d91-9882-a32aef131414]
└ @ Base loading.jl:1192


RObject{NilSxp}
NULL


In [58]:
@show typeof(R_data)

typeof(R_data) = Dict{String,Any}


Dict{String,Any}

In [59]:
@show typeof(npz_data)

typeof(npz_data) = Array{Int64,2}


Array{Int64,2}

### 줄리아에서 시간 다루기

In [60]:
P

73×2 Array{Any,2}:
 1951  "Regional Assembly Language"
 1952  "Autocode"                  
 1954  "IPL"                       
 1955  "FLOW-MATIC"                
 1957  "FORTRAN"                   
 1957  "COMTRAN"                   
 1958  "LISP"                      
 1958  "ALGOL 58"                  
 1959  "FACT"                      
 1959  "COBOL"                     
 1959  "RPG"                       
 1962  "APL"                       
 1962  "Simula"                    
    ⋮                              
 2003  "Scala"                     
 2005  "F#"                        
 2006  "PowerShell"                
 2007  "Clojure"                   
 2009  "Go"                        
 2010  "Rust"                      
 2011  "Dart"                      
 2011  "Kotlin"                    
 2011  "Red"                       
 2011  "Elixir"                    
 2012  "Julia"                     
 2014  "Swift"                     

In [61]:
# Q1: Which year was was a given language invented?
function year_created(P, language::String)
    loc = findfirst(P[:,2] .== language)
    return P[loc,1]
end
year_created(P,"Julia")

2012

In [62]:
year_created(P,"W")

ArgumentError: ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output instead.

In [84]:
isnothing(::Any) = false
isnothing(::Nothing) = true

function year_created_handle_error(P,language::String)
    loc = findfirst(P[:,2] .== language)
    !isnothing(loc) && return P[loc,1]
    error("Error: Language not found.")
end


year_created_handle_error (generic function with 1 method)

In [85]:
year_created_handle_error(P,"W")

ErrorException: Error: Language not found.

In [86]:
# Q2: How many languages were created in a given year?
function how_many_per_year(P,year::Int64)
    year_count = length(findall(P[:,1].==year))
    return year_count
end
how_many_per_year(P,2011)

4

In [87]:
P_df = C #DataFrame(year = P[:,1], language = P[:,2]) # or DataFrame(P)

73×2 DataFrame
 Row │ year   language                   
     │ Int64  String                     
─────┼───────────────────────────────────
   1 │  1951  Regional Assembly Language
   2 │  1952  Autocode
   3 │  1954  IPL
   4 │  1955  FLOW-MATIC
   5 │  1957  FORTRAN
   6 │  1957  COMTRAN
   7 │  1958  LISP
   8 │  1958  ALGOL 58
   9 │  1959  FACT
  10 │  1959  COBOL
  11 │  1959  RPG
  ⋮  │   ⋮                ⋮
  64 │  2006  PowerShell
  65 │  2007  Clojure
  66 │  2009  Go
  67 │  2010  Rust
  68 │  2011  Dart
  69 │  2011  Kotlin
  70 │  2011  Red
  71 │  2011  Elixir
  72 │  2012  Julia
  73 │  2014  Swift
                          52 rows omitted

In [88]:
# Q1: Which year was was a given language invented?
# it's a little more intuitive and you don't need to remember the column ids
function year_created(P_df,language::String)
    loc = findfirst(P_df.language .== language)
    return P_df.year[loc]
end
year_created(P_df,"Julia")

2012

In [89]:
function year_created_handle_error(P_df,language::String)
    loc = findfirst(P_df.language .== language)
    !isnothing(loc) && return P_df.year[loc]
    error("Error: Language not found.")
end
year_created_handle_error(P_df,"W")

ErrorException: Error: Language not found.

In [90]:
# Q2: How many languages were created in a given year?
function how_many_per_year(P_df,year::Int64)
    year_count = length(findall(P_df.year.==year))
    return year_count
end
how_many_per_year(P_df,2011)

4

### missing data

- Julia provides support for representing missing values in the statistical sense, that is for situations where no value is available for a variable in an observation, but a valid value theoretically exists. Missing values are represented via the missing object, which is the singleton instance of the type Missing. missing is equivalent to NULL in SQL and NA in R, and behaves like them in most situations.

- 줄리아는 결측치에 대해 R에서 NA를 사용하듯 missing 이라는 오브젝트를 사용함

- https://docs.julialang.org/en/v1/manual/missing/

In [91]:
# assume there were missing values in our dataframe
P[1,1] = missing
P_df = DataFrame(year = P[:,1], language = P[:,2])

73×2 DataFrame
 Row │ year     language                   
     │ Any      Any                        
─────┼─────────────────────────────────────
   1 │ missing  Regional Assembly Language
   2 │ 1952     Autocode
   3 │ 1954     IPL
   4 │ 1955     FLOW-MATIC
   5 │ 1957     FORTRAN
   6 │ 1957     COMTRAN
   7 │ 1958     LISP
   8 │ 1958     ALGOL 58
   9 │ 1959     FACT
  10 │ 1959     COBOL
  11 │ 1959     RPG
  ⋮  │    ⋮                 ⋮
  64 │ 2006     PowerShell
  65 │ 2007     Clojure
  66 │ 2009     Go
  67 │ 2010     Rust
  68 │ 2011     Dart
  69 │ 2011     Kotlin
  70 │ 2011     Red
  71 │ 2011     Elixir
  72 │ 2012     Julia
  73 │ 2014     Swift
                            52 rows omitted

In [92]:
# 결측치 제거에 dropmissing이라는 함수를 사용할 수 있음
dropmissing(P_df)

# R의 na.omit 과 유사
# If na.omit removes cases, the row numbers of the cases form the "na.action" attribute of the result, of class "omit".

72×2 DataFrame
 Row │ year  language   
     │ Any   Any        
─────┼──────────────────
   1 │ 1952  Autocode
   2 │ 1954  IPL
   3 │ 1955  FLOW-MATIC
   4 │ 1957  FORTRAN
   5 │ 1957  COMTRAN
   6 │ 1958  LISP
   7 │ 1958  ALGOL 58
   8 │ 1959  FACT
   9 │ 1959  COBOL
  10 │ 1959  RPG
  11 │ 1962  APL
  ⋮  │  ⋮        ⋮
  63 │ 2006  PowerShell
  64 │ 2007  Clojure
  65 │ 2009  Go
  66 │ 2010  Rust
  67 │ 2011  Dart
  68 │ 2011  Kotlin
  69 │ 2011  Red
  70 │ 2011  Elixir
  71 │ 2012  Julia
  72 │ 2014  Swift
         51 rows omitted